Vagrant.configure('2') do |config|
    vm_box = 'centos/7'

    config.vm.define :manager, primary: true  do |manager|
        manager.vm.box = vm_box
        manager.vm.box_check_update = true
        manager.vm.network :private_network, ip: "10.0.0.100"
        manager.vm.network :forwarded_port, guest: 22, host: 2220
        
        manager.vm.hostname = "manager"
        manager.vm.synced_folder ".", "vagrant"
        manager.vm.provision "shell", inline: $install_docker_script, privileged: true
        manager.vm.provision "shell", inline: $manager_script, privileged: true
        manager.vm.provider "virtualbox" do |vb|
          vb.name = "manager"
          vb.memory = "1024"
        end
      end
    (1..2).each do |i|
        config.vm.define "worker0#{i}" do |worker|
          worker.vm.box = vm_box
          worker.vm.box_check_update = true
          worker.vm.network :private_network, ip: "10.0.0.10#{i}"
          manager.vm.network :forwarded_port, guest: 22, host: "222#{i}"
          worker.vm.hostname = "worker0#{i}"
          worker.vm.synced_folder ".", "vagrant"
          worker.vm.provision "shell", inline: $install_docker_script, privileged: true
          worker.vm.provision "shell", inline: $worker_script, privileged: true
          worker.vm.provider "virtualbox" do |vb|
            vb.name = "worker0#{i}"
            vb.memory = "1024"
          end
        end
      end
    end